version: '3'

services:
  app:
    build: ../../test docker
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      MAPQUEST_API_KEY: YOU-API-KEY
    depends_on:
      - h2

  h2:
    image: oscarfonts/h2
    ports:
      - "9092:8082"
